### ISSUE TITLE
邮箱地址问题 (Invalid email address)

### ISSUE THREAD

**Issue by TornadoXuRocket** [AveryLiu/TD-DMN#2]
作者您好，我尝试邮件联系您，向您要一下LDC相关数据集处理后的数据集，但是发现您论文中给的邮箱地址错误，能否给一下可用的邮箱地址，谢谢了

**Comment by AveryLiu** [comment]
Sorry for the inconvenience, the email address listed in the paper was revoked after I graduated from school. Please use liushaobo16@mails.ucas.ac.cn instead.

**Comment by TornadoXuRocket** [comment]
Ok, thank you very much.
