### ISSUE TITLE
Data split

### ISSUE THREAD

**Issue by xixy** [AveryLiu/TD-DMN#5]
Thank you for releasing the source code for TD-DMN.

Would you kindly send me the data split used in the 5-fold experiment? I have license for ACE 2005 and sent email to liushaobo@software.ict.ac.cn. My email address is xixy@pku.edu.cn.

Thank you and look forward to your reply.

**Comment by AveryLiu** [comment]
Please send your license to liushaobo16@mails.ucas.ac.cn :)
